In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sympy as sy

from IPython.display import display, Math, Latex

import log_reg

def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [50]:
X_raw = np.array([[450, 0],
             [300, 10],
             [380, 45],
             [250, 20],
             [400, 15]])
Y = np.array([1, 0, 1, 0, 1])
X = np.zeros_like(X_raw, dtype=float)
W = np.ones((1, 2), dtype=float)
b = 0
for j in range(X.shape[1]):
    vals = X_raw[:,j]
    X[:, j] = (vals-vals.min())/(vals.max()-vals.min())

In [41]:
X

array([[1.        , 0.        ],
       [0.25      , 0.22222222],
       [0.65      , 1.        ],
       [0.        , 0.44444444],
       [0.75      , 0.33333333]])

In [18]:
vals = X[:,j]
(vals-vals.min())/(vals.max()-vals.min())

array([0.        , 0.22222222, 1.        , 0.44444444, 0.33333333])

In [24]:
vals

array([ 0, 10, 45, 20, 15])

In [38]:
X

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [52]:
z = X @ W.T + b

In [55]:
yhat = sigmoid(X @ W.T + b)
yhat

array([[0.73105858],
       [0.61590959],
       [0.83889105],
       [0.60931754],
       [0.74712427]])

In [54]:
Y

array([1, 0, 1, 0, 1])

In [58]:

def loss_LCE(Y: np.array, pred: np.array):
    """
    Returns the cross entropy loss for the specified
    data labels and predictions

    Args:
        Y (np.array): Actual labels for the dataset (n rows, 1 column)
        pred (np.array): Predicted labels for the data (n rows, 1 column)

    Returns:
        loss function value (float)
    """
    total_loss = 0
    for i in range(len(Y)):
        # 1 Label
        if Y[i]:
            total_loss += -np.log(pred[i])
        # 0 label
        else:
            total_loss += -np.log(1-pred[i])
    return total_loss/Y.shape[0]


In [59]:
loss_LCE(Y, yhat)

array([0.53543947])

In [67]:
diff = yhat.reshape((5, 1)) - Y.reshape((5,1))

In [81]:
W2 = W - (diff.T @ X)/5
W2

array([[1.08186833, 0.96754485]])

In [82]:
b2 = b-np.mean(diff)
b2

-0.10846020594223263

In [70]:
np.sum(diff)

0.5423010297111631

In [83]:
pred2 = sigmoid(X @ W2.T + b2)
pred2

array([[0.72579829],
       [0.5931534 ],
       [0.82668301],
       [0.57970432],
       [0.736034  ]])

In [84]:
loss_LCE(Y, pred2)

array([0.51668239])

In [77]:
yhat

array([[0.73105858],
       [0.61590959],
       [0.83889105],
       [0.60931754],
       [0.74712427]])

In [85]:
0.5 - 0.15*3

0.050000000000000044

In [86]:
0.005+0.15*3.9

0.59

In [87]:
1.18-4

-2.8200000000000003

In [88]:
0.59 + 0.15*2.82

1.013

In [89]:
2.026-4

-1.9740000000000002

In [90]:
1.1013+0.15*1.974

1.3974

In [92]:
2*1.3974 - 4

-1.2052

In [95]:
-2*np.log(0.01)

9.210340371976182