In [1]:
import scipy as sp
import numpy as np
import matplotlib.pyplot as plt

In [4]:
img = np.array([[[6, 5, -1,-4],
                 [7, 4,  8, 6],
                 [4, 2, -1, 5],
                 [-6, 6, 3, 9]],

                 [[1, 1, 1, 0],
                  [0, 1,  1, 1],
                  [0, 0,  1, 1],
                  [0, 0,  1, 1]],

                 [[33, 17, 23, 4],
                  [11, 19, 14, 51],
                  [2,   1,  5, 8],
                  [0,   6,  0, 1]]
                 ])

filter = np.array([[[4, 3, 4],
                    [2, 4, 3],
                    [2, 3, 4]],

                    [[1, 0, -1],
                     [1, 0, -1],
                     [1, 0, -1]],

                    [[1, 1, 1],
                     [0, 1, 1],
                     [0, 0, 1]]
                    ])

bias = 1

In [20]:
20-3-16+8+32+18+4-3+20

80

In [21]:
28+12+32+8+8-3-12+18+12

103

In [22]:
16+24+24+4-4+15+12+9+36

136

In [23]:
33+17+23+19+14+5

111

In [24]:
17+23+4+14+51+8

117

In [25]:
11+19+14+1+5+0

50

In [26]:
19+14+51+5+8+1

98

In [16]:
res = []
for ch in range(img.shape[0]):
    res.append(sp.signal.correlate2d(img[ch], filter[ch], mode="valid")) 

In [17]:
res

[array([[ 99,  80],
        [103, 136]]),
 array([[-2,  0],
        [-3, -2]]),
 array([[111, 117],
        [ 50,  98]])]

In [18]:
z = sum(res) + bias
z

array([[209, 198],
       [151, 233]])

In [19]:
z.flatten()

array([209, 198, 151, 233])

In [32]:
sp.ndimage.maximum_filter(img[0],2, mode="nearest")

array([[ 6,  6,  5, -1],
       [ 7,  7,  8,  8],
       [ 7,  7,  8,  8],
       [ 4,  6,  6,  9]])